<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Twilio" Version="7.13.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Contract\NotificationService.Contract.csproj" />
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\NotificationService.Infrastructure\NotificationService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
