// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;

#nullable disable

namespace NotificationService.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250928074805_NotificationMig1")]
    partial class NotificationMig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.Master.NotificationChannelMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("NotificationChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Email notifications",
                            IsActive = true,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "SMS notifications",
                            IsActive = true,
                            Name = "SMS"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "In-App notifications",
                            IsActive = true,
                            Name = "InApp"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "No channel selected",
                            IsActive = true,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Master.NotificationStatusMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("NotificationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Notification is pending",
                            IsActive = true,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Notification sent successfully",
                            IsActive = true,
                            Name = "Sent"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Notification failed to deliver",
                            IsActive = true,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Master.NotificationTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Order placed confirmation",
                            IsActive = true,
                            Name = "OrderPlaced"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Payment successful confirmation",
                            IsActive = true,
                            Name = "PaymentSuccess"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Payment failure alert",
                            IsActive = true,
                            Name = "PaymentFailed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Order shipment update",
                            IsActive = true,
                            Name = "OrderShipped"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Order delivery confirmation",
                            IsActive = true,
                            Name = "OrderDelivered"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Order cancellation notification",
                            IsActive = true,
                            Name = "OrderCancelled"
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "General purpose notifications",
                            IsActive = true,
                            Name = "General"
                        });
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemplateData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationAttachments");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationAttemptLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("ChannelId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("StatusId");

                    b.ToTable("NotificationAttemptLogs");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDefault");

                    b.HasIndex("TemplateName");

                    b.HasIndex("TypeId");

                    b.ToTable("NotificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ChannelId = 1,
                            Content = "Hello {CustomerName},<br/>Your order #{OrderNumber} has been placed successfully.<br/>Items: {Items}<br/>Total Amount: ₹{Amount}.<br/>We will notify you once it is shipped.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Your Order #{OrderNumber} is Confirmed!",
                            TemplateName = "OrderPlaced_Email",
                            TypeId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            ChannelId = 2,
                            Content = "Hi {CustomerName}, your order #{OrderNumber} of ₹{Amount} is placed successfully.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Order Confirmation",
                            TemplateName = "OrderPlaced_SMS",
                            TypeId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            ChannelId = 1,
                            Content = "Dear {CustomerName},<br/>We have received your payment of ₹{Amount} for order #{OrderNumber}.<br/>Thank you for shopping with us.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Payment Received for Order #{OrderNumber}",
                            TemplateName = "PaymentSuccess_Email",
                            TypeId = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ChannelId = 2,
                            Content = "Hi {CustomerName}, your payment of ₹{Amount} for order #{OrderNumber} has failed. Please retry.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Payment Failed",
                            TemplateName = "PaymentFailed_SMS",
                            TypeId = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            ChannelId = 1,
                            Content = "Hello {CustomerName},<br/>Your order #{OrderNumber} has been shipped.<br/>Track your order here: {TrackingLink}.<br/>Thank you for shopping with us!",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Your Order #{OrderNumber} has been Shipped!",
                            TemplateName = "OrderShipped_Email",
                            TypeId = 4,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            ChannelId = 2,
                            Content = "Hi {CustomerName}, your order #{OrderNumber} has been shipped. Track here: {TrackingLink}",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Order Shipped",
                            TemplateName = "OrderShipped_SMS",
                            TypeId = 4,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ChannelId = 3,
                            Content = "Your order #{OrderNumber} has been shipped. Tap to track.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Order Update",
                            TemplateName = "OrderShipped_InApp",
                            TypeId = 4,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            ChannelId = 1,
                            Content = "Dear {CustomerName},<br/>Your order #{OrderNumber} has been successfully delivered.<br/>We hope you enjoy your purchase!",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Your Order #{OrderNumber} has been Delivered",
                            TemplateName = "OrderDelivered_Email",
                            TypeId = 5,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            ChannelId = 2,
                            Content = "Hi {CustomerName}, your order #{OrderNumber} has been delivered. Thank you for shopping with us!",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Order Delivered",
                            TemplateName = "OrderDelivered_SMS",
                            TypeId = 5,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            ChannelId = 3,
                            Content = "Your order #{OrderNumber} has been delivered successfully.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Delivery Update",
                            TemplateName = "OrderDelivered_InApp",
                            TypeId = 5,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            ChannelId = 1,
                            Content = "Dear {CustomerName},<br/>Your order #{OrderNumber} has been cancelled.<br/>If payment was made, refund of ₹{Amount} will be processed shortly.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Your Order #{OrderNumber} has been Cancelled",
                            TemplateName = "OrderCancelled_Email",
                            TypeId = 6,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            ChannelId = 2,
                            Content = "Hi {CustomerName}, your order #{OrderNumber} has been cancelled. Refund of ₹{Amount} will be processed shortly.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Order Cancelled",
                            TemplateName = "OrderCancelled_SMS",
                            TypeId = 6,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            ChannelId = 3,
                            Content = "Your order #{OrderNumber} has been cancelled. Refund will be processed soon.",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EffectiveFrom = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            SubjectTemplate = "Order Cancelled",
                            TemplateName = "OrderCancelled_InApp",
                            TypeId = 6,
                            Version = 1
                        });
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplateAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("NotificationTemplateAudits");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DoNotDisturb")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDailyNotifications")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("QuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("QuietHoursStart")
                        .HasColumnType("time");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationChannelMaster", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationStatusMaster", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationTypeMaster", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationAttachment", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.Notification", "Notification")
                        .WithMany("Attachments")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationAttemptLog", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationChannelMaster", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Domain.Entities.Notification", "Notification")
                        .WithMany("AttemptLogs")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationStatusMaster", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Notification");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationChannelMaster", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Domain.Entities.Master.NotificationTypeMaster", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplateAudit", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.NotificationTemplate", "Template")
                        .WithMany("AuditTrail")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AttemptLogs");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Navigation("AuditTrail");
                });
#pragma warning restore 612, 618
        }
    }
}
